# Trading System Configuration

# Trading Parameters
DAILY_PROFIT_TARGET: 50.0  # EUR
INITIAL_CAPITAL: 10000.0   # EUR
MAX_DAILY_DRAWDOWN: 0.03   # 3%
MAX_WEEKLY_DRAWDOWN: 0.05  # 5%
MAX_MONTHLY_DRAWDOWN: 0.10 # 10%

# Risk Management
MAX_RISK_PER_TRADE: 0.01   # 1% of capital
MAX_POSITION_SIZE: 0.05    # 5% of capital
MAX_CONCURRENT_POSITIONS: 20
STOP_LOSS_MANDATORY: true

# IBKR Configuration
IBKR_HOST: "127.0.0.1"
IBKR_PORT: 7497  # Paper trading port (7496 for live)
IBKR_CLIENT_ID: 1
IBKR_TIMEOUT: 10

# Data Configuration
DATA_STORAGE_PATH: "./data"
LOG_STORAGE_PATH: "./logs"
HISTORICAL_DATA_DAYS: 252  # 1 year

# Strategy Parameters
MEAN_REVERSION:
  BOLLINGER_PERIOD: 20
  BOLLINGER_STD: 2.0
  RSI_PERIOD: 14
  RSI_OVERSOLD: 30
  RSI_OVERBOUGHT: 70
  VOLUME_MULTIPLIER: 1.5
  MAX_HOLD_DAYS: 5
  STOP_LOSS_PCT: 0.02

PAIRS_TRADING:
  CORRELATION_THRESHOLD: 0.7
  CORRELATION_LOOKBACK: 126  # 6 months
  ZSCORE_ENTRY: 2.0
  ZSCORE_EXIT: 0.5
  ZSCORE_STOP: 3.0
  MAX_HOLD_DAYS: 10
  COINTEGRATION_PVALUE: 0.05

# Screening Parameters
UNIVERSE_FILTERS:
  MIN_DOLLAR_VOLUME: 1000000  # $1M daily
  MAX_BID_ASK_SPREAD: 0.001   # 0.1%
  MIN_PRICE: 5.0
  MAX_PRICE: 500.0
  MIN_MARKET_CAP: 100000000   # $100M
  EXCHANGES: ["NYSE", "NASDAQ"]

# Monitoring
LOG_LEVEL: "INFO"
ENABLE_DASHBOARD: true
DASHBOARD_HOST: "0.0.0.0"
DASHBOARD_PORT: 5000

# Alerts
EMAIL_ALERTS: false
TELEGRAM_ALERTS: false
